# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 05:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_type',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='bikes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='city',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='clubs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='country',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='date_preference',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='email',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='firstname',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='follower',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='follower_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='friend',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='friend_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='ftp',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='lastname',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='measurement_preference',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='mutual_friend_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='profile',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='profile_medium',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='resource_state',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='shoes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='state',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
