# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170720_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='user',
            new_name='stravauser',
        ),
    ]
